version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}

  fastapi:
    build:
      context: ./fast_api
      dockerfile: Dockerfile.api
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/chatops_udv/fast_api/docker/app.sh"]
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  gigachat_api:
    build:
      context: ./gigachat_api
      dockerfile: Dockerfile.gigachat_api
    env_file:
      - ./gigachat_api/.env
    container_name: gigachat_api
    ports:
      - "8080:8080"
    depends_on:
      - fastapi

#  react:
#    build:
#      context: ./react
#      dockerfile: Dockerfile.react
#    container_name: react
#    ports:
#      - "3000:3000"