version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      DB_PASS: ${DB_PASS}
    command: -p 5433
    expose:
      - 5433

  fastapi:
    build:
      context: ./fast_api
      dockerfile: Dockerfile.api
    env_file:
      - ./fast_api/.env
    container_name: fastapi_app
    command: ["/chatops_udv/docker/app.sh"]
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  gigachat_api:
    build:
      context: ./gigachat_api
      dockerfile: Dockerfile.gigachat_api
    env_file:
      - ./gigachat_api/.env
    container_name: gigachat_api
    ports:
      - "8001:8001"

  react:
    build:
      context: ./react
      dockerfile: Dockerfile.react
    container_name: react
    ports:
      - "3000:3000"