version: '3'
services:
  fastapi:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5433"
    env_file:
      - .env