"""update user

Revision ID: 43698e996303
Revises: 0f5c1f414b85
Create Date: 2024-02-26 01:13:11.107538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43698e996303'
down_revision: Union[str, None] = '0f5c1f414b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_representative', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company_representative')
    # ### end Alembic commands ###
