"""add doc2

Revision ID: 8481e6b97962
Revises: 6d8203b30d76
Create Date: 2024-03-01 11:32:48.157435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8481e6b97962'
down_revision: Union[str, None] = '6d8203b30d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'doc', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doc', type_='unique')
    # ### end Alembic commands ###
